#!/bin/bash
cat <<EOF > typescript_discord_bot_job_search/.env
DB_DEPENDENCY_NAME=${DB_DEPENDENCY_NAME}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
ADMINER_PORT=${ADMINER_PORT}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
EOF
echo ".env file generated successfully."
